### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by sampablokuper** [trezor/trezor-hw#2]
The files in this repository appear not to have a license specified for them.

Please can you add to the repo:
- a copy of the relevant license, and
- a notice stating who owns the copyright in the files, and stating that the copyright holder is making them available under the license above.

Ideally, please use [this license (the AGPLv3)](https://www.gnu.org/licenses/agpl-3.0.html).

Thank you.

**Comment by xaionaro** [comment]
Will there be any reaction on this?

**Comment by prusnak** [comment]
Fixed in https://github.com/trezor/trezor-hw/commit/2783997e27c9ea5fd2ff9b8afffb980c6326d09d

**Comment by xaionaro** [comment]
Thank you! :)
