### ISSUE TITLE
3D case 

### ISSUE THREAD

**Issue by juttTechnology** [trezor/trezor-hw#6]
any one have updated 3D model files for Version 1.1
i already print the current files but have two issues.
1. button are very tight inside the case
2. back cover is not fitting because it looks small.

thank you

**Comment by prusnak** [comment]
Use the files from https://github.com/trezor/trezor-hw/tree/master/case/3dPrint

Several people have successfully used these. If it still doesn't work, try to fiddle with your printer's settings.
